sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yashvanthkumar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yashvanthkumar/docker-react npm run test
  
deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-225560313378"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

