sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t yashvanthkumar/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yashvanthkumar/docker-react npm run test

